name: Security

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  trufflehog:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog secret scan
        uses: trufflesecurity/trufflehog@v3.63.7
        with:
          extra_args: --only-verified --exclude-paths=/tmp/.trufflehog-exclude.txt
